name: Deploy Storefront

on:
  push:
    branches:
      - main # Or your primary deployment branch for storefront
    paths: # Only run if files in these paths change
      - '212storefront/**' # Adjust if it's in a monorepo, e.g., 'apps/storefront/**'
      - '.github/workflows/deploy-storefront.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This checks out the repo where the workflow file resides

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3 # Or latest version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e # Exit on error
            echo "Deploying storefront to /var/www/212manager-app/212storefront..."
            cd /var/www/212manager-app/212storefront
            
            echo "Pulling latest changes..."
            git fetch origin main # Fetch latest from main
            git reset --hard origin/main # Reset local to match remote
            git pull origin main
            
            echo "Creating .env file from secret..."
            echo "${{ secrets.STOREFRONT_ENV }}" > .env
            
            echo "Removing .next cache..."
            rm -rf .next/cache
            
            echo "Installing dependencies..."
            npm install
            # npm audit fix # Optional in CI
            
            echo "Building storefront..."
            npm run build
            
            echo "Restarting PM2 process for 212storefront..."
            pm2 restart 212storefront
            pm2 save
            echo "Storefront deployment complete."
            pm2 list
